# Generated by Django 5.1.4 on 2024-12-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории проекта')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес категории')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='constructio_name_b0cd18_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Фото проекта')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/', verbose_name='Видео проета')),
                ('youtube_url_video', models.URLField(blank=True, null=True, verbose_name='YouTube видео')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='construction.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='constructio_slug_842b69_idx'), models.Index(fields=['name'], name='constructio_name_27697d_idx')],
            },
        ),
    ]
