# Generated by Django 5.1.4 on 2024-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
    ]
